# Generated by Django 4.2.3 on 2026-02-10 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_order_cancelledat_order_iscancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='helpfulVotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='isApproved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='review',
            name='isReported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='base.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
