# Generated by Django 4.2.3 on 2026-02-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_review_helpfulvotes_review_isapproved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
